# Generated by Django 3.2 on 2023-01-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_page', '0002_alter_siteregister_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitealert',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
