# Generated by Django 3.2 on 2023-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_page', '0003_sitealert_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteregister',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
